"""Add category, summary_text, fact_check_results to Article

Revision ID: add_category_summary_factcheck
Revises: 651bc5ed60f4
Create Date: 2025-07-13 10:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_category_summary_factcheck'
down_revision = '651bc5ed60f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('summary_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fact_check_results', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('fact_check_results')
        batch_op.drop_column('summary_text')
        batch_op.drop_column('category')

    # ### end Alembic commands ### 